def crawlcode():
    print("CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL")
    print("CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL")
    print("CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL")
    print("CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL CRAWL")