def recprint():
    print("REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC")
    print("REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC")
    print("REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC")
    print("REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC REC")